import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Hero } from "@/components/Hero";
import { Sample } from "@/components/Sample";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "移加租屋",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ // may delete Readonly later to test the setting
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
