import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { useClerkJWT } from "./api/Clerk-user/route";
import { AuthProvider } from './Context/AuthContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "移加租屋",
  description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{ // may delete Readonly later to test the setting
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <AuthProvider>
              <Navbar/>
                    {children}
                  <Footer/>
          </AuthProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
